#include<iostream.h>
#include<conio.h>

float area pi=3.14;

float area(float r)
{
 return(pie*r*);
}

float area(float l, float b)
{
 return(l*b)
}
void main()
{
float radius;
cout<<"enter the radius:">>endl;
cin>>radius;
cout<<"area of circle:">>area(radius);

float length;
cout<<"enter length:"<<endl;
cin>>length;
cout<<"enter breadth:"<<endl;
cin>>breadth;
cout<<"area of rectangle:"<<area(length,breadth)<<endl;
return 0;
}
